### PR TITLE
Hiera

### PR DESCRIPTION
**Pull request by propyless**
Hi,

I added hiera support to this module and also tested out the changes in #6 because that is one of the features we require.

I based my additions for hiera to the puppet fileserver branch. (Since the other person who requested it has not tested it, I've also done that and it works splendidly.)

### CODE REVIEW

**Comment by propyless** [comment]
Hello,

Anyone who can take a look at this PR?

**Comment by propyless** [comment]
Hello, anyone wanna take a look at this?

**Comment by propyless** [comment]
Alright, I removed the define, I added fixtures to simulate the hiera data and also I got the spec tests working with ruby 1.8.7 but for some reason the tests I added for the hiera class do not work and I am unsure whats causing them to fail since it works with the newer rspec version.

**Comment by propyless** [comment]
Ok, I changed the logic for determining which rspec gem to use and  I switch to rspec 3.1.0. but it still fails for puppet v2~

**Comment by propyless** [comment]
@stschulte  ping - you got any ideas?

**Comment by propyless** [comment]
Added some notifies.. and rspec tests to see what message the notifies contains.. doesnt seem like it can get the data from hiera on puppetversion 2.7~. I've been trying for a couple of days now to get it working but I am unable to do so.
Is it alright to drop support for 2.7?

**Comment by propyless** [comment]
@stschulte ping

**Comment by genebean** [comment]
@propyless Are you maintaining a fork with your changes?

**Comment by propyless** [comment]
@genebean Nope, not at all. I haven't worked with Puppet for many years now. and looking at the PR there hasn't been a single response so I thought it'd be time to close this PR.
Looks like the repo owner/maintainer has merged some things in 2021 so hes alive at least.

You are welcome to cherrypick/fork the branch if you still need it. but I don't have to delete my fork either.. but its probably safest that you fork it yourself :)

**Comment by stschulte** [comment]
Wow this has been a long time. I am sorry for not responding here, I remember back in the days I was not really happy with the fileserver hack that this MR is based on, but I should have worked with you to factor the hiera change to its own MR. However I have not touched puppet myself in years and did not follow its development. I did one attempt to at least make sure the modules would still build/test but without using puppet anywhere right now there is not really a great incentive at the moment.

**Pull request closed without merging**
